# Generated by Django 4.2.1 on 2026-01-30 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_image_path",
                    models.CharField(help_text="元画像のパス", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "problems",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LatexDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latex_code", models.TextField(help_text="LaTeXコード")),
                (
                    "pdf_path",
                    models.CharField(blank=True, help_text="生成PDFのパス", max_length=500),
                ),
                ("version", models.IntegerField(default=1, help_text="バージョン番号")),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, help_text="ユーザーが確認済みかどうか"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latex_documents",
                        to="app.problem",
                    ),
                ),
            ],
            options={
                "db_table": "latex_documents",
                "ordering": ["problem", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Explanation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("explanation_latex", models.TextField(help_text="解説のLaTeXコード")),
                (
                    "explanation_pdf_path",
                    models.CharField(blank=True, help_text="解説PDFのパス", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latex_document",
                    models.ForeignKey(
                        help_text="解説生成時に確認済みだったLaTeXドキュメント",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanations",
                        to="app.latexdocument",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanations",
                        to="app.problem",
                    ),
                ),
            ],
            options={
                "db_table": "explanations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["user", "-created_at"], name="problems_user_id_ec01ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="latexdocument",
            index=models.Index(
                fields=["problem", "-version"], name="latex_docum_problem_1efc67_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="latexdocument",
            unique_together={("problem", "version")},
        ),
        migrations.AddIndex(
            model_name="explanation",
            index=models.Index(
                fields=["problem", "-created_at"], name="explanation_problem_029d9a_idx"
            ),
        ),
    ]
