# Generated by Django 4.2.1 on 2026-02-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_update_system_default_template_japanese'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='latextemplate',
            new_name='latex_templ_user_id_5e816f_idx',
            old_name='app_latext_user_id_2a3f4e_idx',
        ),
    ]
